version: '3.4'

services:
  exti.spa:
    image: ${DOCKER_REGISTRY}extispa
    build:
      context: .
      dockerfile: Exti-SPA/Dockerfile

  exti.api:
    image: ${DOCKER_REGISTRY}extiapi
    build:
      context: .
      dockerfile: Exti.API/Dockerfile
